name: 'Add asset to release'
description: 'Upload an asset, e.g. a binary file, to an already-existing GitHub release.'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  token:
    description: 'GitHub token with permission to upload. The GITHUB_TOKEN provided to a workflow should be enough.'
    required: true
  path:
    description: 'File to upload. Does not support wildcards.'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
